global:
  smtp_from: 'karthikkunchala2307@gmail.com'
  smtp_smarthost: smtp.gmail.com:587
  smtp_auth_username: 'karthikkunchala2307@gmail.com'
  smtp_auth_identity: 'karthikkunchala2307@gmail.com'
  smtp_auth_password: 'enter_gmail_app_password'  

route:
  #fallback default receiver
  receiver: admin
  group_wait: 40s
  group_interval: 5m
  repeat_interval: 2h
  routes:
  - match_re:
      app_type: (linux|windows)
    receiver: ss-admin
    routes:
    - match_re:
        app_type: linux 
      receiver: linux-admin
      group_by: [category]
      routes:
      - match:
          severity: critical
        receiver: linux-team-manager
        continue: true
      - match:
          severity: warning
        receiver: linux-team-lead
      - match:
          severity: critical
        receiver: better-stack

    - match_re:
        app_type: windows 
      receiver: windows-admin
      group_by: [category]
      routes:
      - match:
          severity: critical
        receiver: windows-team-manager
      - match: 
          severity: warning
        receiver: windows-team-lead

# for python and go application
  - match_re:
      app_type: (python|go)
    receiver: pec-admin
    routes:
    - match:
        app_type: python
      receiver: python-team-admin
      group_by: [category]
      routes:
      - match:
          severity: critical
        receiver: python-team-manager
      
      - match:
          severity: warning
        receiver: python-team-lead

    - match:
        app_type: go
      receiver: go-team-admin
      group_by: [category]
      routes:
      - match:
          severity: critical
        receiver: go-team-manager
      
      - match:
          severity: warning
        receiver: go-team-lead

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['app_type', 'category']



receivers:
- name: admin
  email_configs:
  - to: 'karthikkunchala170@gmail.com'

- name: ss-admin
  email_configs:
  - to: 'karthikkunchala2398@gmail.com'

- name: linux-admin
  email_configs:
  - to: 'karthikkunchala170@gmail.com'

- name: linux-team-lead
  email_configs:
  - to: 'karthikkunchala2398@gmail.com'

- name: linux-team-manager
  slack_configs:
  - channel: '#prometheus-alerts'
    api_url: 'url_of_pagerduty/better stack'
    title: 'Linux instance issue'
    text: 'Linux instance {{ $labels.instance }} of job {{ $labels.job }} which belongs to group {{ $labels.category }} is having {{ $value }}'

- name: better-stack
  webhook_configs:
    url: 'https://uptime.betterstack.com/api/v1/prometheus/webhook/fWnvnsFYnkpGXN7qutQW74UR'

- name: windows-admin
  email_configs:
  - to: 'karthikkunchala170@gmail.com'

- name: windows-team-lead
  email_configs:
  - to: 'karthikkunchala2398@gmail.com'

- name: windows-team-manager
  email_configs:
  - to: 'karthikkunchala2398@gmail.com'

- name: pec-admin
  email_configs:
  - to: 'karthikkunchala2398@gmail.com'

- name: python-team-admin
  email_configs:
  - to: 'karthikkunchala170@gmail.com'

- name: python-team-lead
  email_configs:
  - to: 'karthikkunchala2398@gmail.com'

- name: python-team-manager
  email_configs:
  - to: 'karthikkunchala2398@gmail.com'

- name: go-team-admin
  email_configs:
  - to: 'karthikkunchala170@gmail.com'

- name: go-team-lead
  email_configs:
  - to: 'karthikkunchala2398@gmail.com'

- name: go-team-manager
  email_configs:
  - to: 'karthikkunchala2398@gmail.com'

